# Standards: 0.1
---
- name: Kill istat-menus
  command: killall iStat\ Menus
  register: istat_menus_kill
  failed_when: istat_menus_kill.rc != 0 and "No matching processes belonging to you were found" not in istat-menus_kill.stderr
  become: "{{ (istat_menus_user != ansible_user_id) | bool }}"
  become_user: "{{ istat_menus_user }}"

- name: Start istat-menus
  when: istat_menus_started
  command: open -j /Applications/iStat\ Menus.app
  become: "{{ (istat_menus_user != ansible_user_id) | bool }}"
  become_user: "{{ istat_menus_user }}"

...
